### ISSUE TITLE
Not compiling on odroid u3

### ISSUE THREAD

**Issue by rs1990** [ethz-asl/vicon_bridge#13]
Hello,
I have been trying to get the package working on my system, however its not working. I am not able to catkin_make it successfully. Im using ROS indigo. 

This is the error i keep getting. HELP PLEASE!!

```
Scanning dependencies of target vicon_bridge_generate_messages_cpp
[ 60%] Generating C++ code from vicon_bridge/Markers.msg
[ 62%] Built target msf_core
Scanning dependencies of target vicon_bridge_generate_messages_py
[ 63%] Generating Python from MSG vicon_bridge/Markers
Linking CXX executable /home/odroid/indigo_ws/devel/lib/vicon_bridge/testclient
/usr/bin/ld.bfd.real: skipping incompatible /home/odroid/indigo_ws/src/vicon_bridge/vicon_sdk/Vicon_SDK_1.3_Linux/32-bit/libViconDataStreamSDK_CPP.so when searching for -lViconDataStreamSDK_CPP
/usr/bin/ld.bfd.real: cannot find -lViconDataStreamSDK_CPP
collect2: error: ld returned 1 exit status
make[2]: *** [/home/odroid/indigo_ws/devel/lib/vicon_bridge/testclient] Error 1
make[1]: *** [vicon_bridge/CMakeFiles/testclient.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Thanks

**Comment by kdhansen** [comment]
The vicon_bridge depends on the closed-source library ViconDataStreamSDK supplied from Vicon in binary form. The shared library is not compatible with your odroid, thus it will not compile. I think you are out of luck; Vicon will probably not compile the library for odroid.

Have a look at issues #10 and #8 

Best,
Karl
