### ISSUE TITLE
could not build on ubuntu-mate 16.04

### ISSUE THREAD

**Issue by Abelteklu** [ethz-asl/vicon_bridge#19]
Hello.
I am trying to build vicon_bridge from catkin_ws on ubuntu-mate 16.04 installed on raspberry pi 3. The procedure that  I followed for the build is,
1- Download ViconDataStreamSDK from company website to /home/pi/Documents/.
2- Download vicon_bridge from this repository to catkin_ws/src.
3- Set the library path as, 
export LD_LIBRARY_PATH=/home/pi/Documents/ViconDataStreamSDK_1.7.1_96542h/Linux32-boost-1.55.0/20170125_96542h.x86/:$LD_LIBRARY_PATH 
4- catkin build

However, I am geting a build error as,

Errors     << vicon_bridge:make /home/pi/catkin_ws/logs/vicon_bridge/build.make.010.log
make[2]: *** No rule to make target '/usr/bin/libViconDataStreamSDK_CPP.so', needed by '/home/pi/catkin_ws/devel/.private/vicon_bridge/lib/vicon_bridge/testclient'.  Stop.
make[1]: *** [CMakeFiles/testclient.dir/all] Error 2
make: *** [all] Error 2
cd /home/pi/catkin_ws/build/vicon_bridge; catkin build --get-env vicon_bridge | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << vicon_bridge:make           [ Exited with code 2 ]               
Failed    <<< vicon_bridge                [ 3.0 seconds ]                      
[build] Summary: 0 of 1 packages succeeded.                                    
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 3.1 seconds total.

catkin_make is also not working. Can someone help me? 

Thank you so much.

**Comment by cdlwhm1217096231** [comment]
I have meet this same problem,how to settle this problem?thanks...

**Comment by Abelteklu** [comment]
Hi @cdlwhm1217096231, It never worked for me on 16.04. To solve the problem, I installed Ubuntu 14.04 on my laptop and received the Vicon data. Following this, I used ROS Multimaster Fkie (http://wiki.ros.org/multimaster_fkie) to share the data with my raspberry pi 3 (which has Ubuntu mate 16.04 installed on it) and my laptop (which has Ubuntu 14.04 installed on it).

**Comment by cdlwhm1217096231** [comment]
thank you,my raspberry pi 3 has installed ubuntu 16.04, how to receive the vicon data and use it for fix my robot navigation

**Comment by Abelteklu** [comment]
U re welcome :) Install Ubuntu 14.04 on another computer and receive the vicon data. Then share the data with your raspberry pi 3 using ros multimaster fkie.

**Comment by cdlwhm1217096231** [comment]
ok,thank you!
