### ISSUE TITLE
Exception 'boost::thread_interrupted'

### ISSUE THREAD

**Issue by pomerlef** [ethz-asl/vicon_bridge#6]
Thanks for the node! We are having some exception thrown every randomly 20% of the time we are using the node.

Background info:
- Ubuntu 12.04
- ROS Hydro
- Boost version: 1.46.1.7

Trace:

[ INFO] [1417737946.520509880]: setting up grab_vicon_pose service server ... 
[ INFO] [1417737946.522555280]: setting up segment calibration service server ... 
[ WARN] [1417737946.525454880]: grab frame returned false
terminate called after throwing an instance of 'boost::thread_interrupted'
[vicon-2] process has died [pid 25573, exit code -6, cmd /home/asrl/banff/utias/devel/lib/vicon_bridge/vicon_bridge __name:=vicon __log:=/home/asrl/.ros/log/7549afc2-7c12-11e4-93a3-f81edfde4c6d/vicon-2.log].
log file: /home/asrl/.ros/log/7549afc2-7c12-11e4-93a3-f81edfde4c6d/vicon-2*.log

**Comment by CatherineH** [comment]
building in release mode (catkin_make -DCMAKE_BUILD_TYPE=Release) seemed to get rid of this issue for me.

**Comment by CatherineH** [comment]
okay, now I get this error even with that build, so I think it is unrelated. 
I've noticed that I get this error when I run the vicon_bridge with a previous vicon node still running. Killing the vicon node and cleaning up seems to clear the issue.

**Comment by jasonimercer** [comment]
The problem may be derived from slightly different versions of boost between the ones included in Vicon SDK (1.53.0) and on the ones used on the ROS side. I'm going to look and see if there's a simple fix.
