### ISSUE TITLE
Indigo Release

### ISSUE THREAD

**Issue by paulbovbel** [ethz-asl/vicon_bridge#8]
Hi there, would the maintainer(s) be willing to release vicon_bridge for ROS Indigo? It would be greatly appreciated!

**Comment by markusachtelik** [comment]
Dear Paul, I got the feedback that it's running under indigo already. If anything is missing, I'm also happy to accept pull-requests ;)

**Comment by paulbovbel** [comment]
Will do, I have a few things I'd like to push in the near future.

I meant a debian release onto the ROS buildfarm - vicon_bridge hasn't had a release since groovy, and it's much more convenient to work with binaries.

**Comment by markusachtelik** [comment]
sounds great! Debians would be very convenient indeed. I just don't know how to include the Datastream binaries into that. The cleanest way would most likely be to switch to vrpn. We have a catkin wrapper for UNC's vrpn implementation, but I couldn't find the time so far to include it: https://github.com/ethz-asl/vrpn_catkin . That would also let us get rid of the awful boost incompatibilities ...

**Comment by paulbovbel** [comment]
Ah, I see, I didn't notice you had the vicon SDK embedded in your source :(

I'll have some experimentation time on a vicon system soon, and I'll take a look at VRPN. It may be cleaner to just develop a vrpn_client package as a fork/rewrite, and leave vicon_bridge intact.
